# PyTorch:Basics

## Tensor

In [1]:
import torch

In [2]:
a = torch.tensor(1.0)
print(a)
print(a.dim())
print(a.shape)#print(a.size())
print(a.dtype)
print(a.item())

tensor(1.)
0
torch.Size([])
torch.float32
1.0


In [3]:
b = torch.tensor([1,2,3])
print(b)
print(b.dim())
print(b.shape)
print(b.dtype)
print(b.numpy())

tensor([1, 2, 3])
1
torch.Size([3])
torch.int64
[1 2 3]


In [4]:
import numpy as np

x = np.array([0,1])
c = torch.from_numpy(x)
c

tensor([0, 1], dtype=torch.int32)

In [5]:
c = torch.tensor([[1,2],[3,4],[5,6]],dtype = torch.int16)
print(c)
print(c.dim())
print(c.shape)
print(c.dtype)
print(c.numpy())

tensor([[1, 2],
        [3, 4],
        [5, 6]], dtype=torch.int16)
2
torch.Size([3, 2])
torch.int16
[[1 2]
 [3 4]
 [5 6]]


In [6]:
d = torch.zeros((3,4))
print(d)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])


In [7]:
e = torch.randn((2,2,3,4))
print(e)

tensor([[[[ 3.4568e-01,  6.0926e-01, -2.8407e+00,  6.9198e-01],
          [ 1.9785e-01, -3.5950e-01, -7.4096e-01, -8.7822e-02],
          [-1.8936e+00, -1.5445e+00, -1.5313e-01, -1.3686e+00]],

         [[ 2.3141e+00, -2.2593e-01,  4.4259e-01, -1.1041e+00],
          [ 1.0801e-01, -3.6021e-01,  4.3309e-01, -2.2172e-01],
          [ 1.1818e+00,  1.7186e-03,  1.0034e+00,  2.5472e-01]]],


        [[[ 1.6120e+00, -8.6260e-01, -4.5354e-01,  1.3883e-01],
          [ 2.9553e-02,  1.2198e+00,  1.3018e+00,  8.1123e-02],
          [-1.3104e+00,  1.0105e-01,  4.7510e-02, -1.6506e-01]],

         [[-5.5756e-01, -2.3901e-01,  1.6148e+00,  8.0101e-02],
          [ 1.0832e+00, -1.3870e+00,  4.9780e-01, -1.9438e+00],
          [-3.0700e-01,  7.9353e-01, -7.4710e-01,  4.5870e-01]]]])


In [8]:
e.stride()

(24, 12, 4, 1)

In [9]:
a = torch.tensor([1.0,2.0])
a[0]

tensor(1.)

In [10]:
a.item()

ValueError: only one element tensors can be converted to Python scalars

In [ ]:
a.numpy()

In [ ]:
b = torch.tensor([[[1,2],[3,4]],
                  [[5,6],[7,8]],
                  [[9,10],[11,12]]
                 ])
b.item()

In [ ]:
b[0].shape

In [ ]:
b[0]

In [ ]:
b[:1]

In [ ]:
b[:1].shape

In [ ]:
b[:,0,0]

In [ ]:
b.storage()

In [ ]:
a = torch.ones((3))
b = a[:2]
print(a)
print(b)

In [ ]:
b[0] = 2
print(a)
print(b)

In [ ]:
c = a[:2].clone()
c[0] = 3
print(a)
print(c)

In [ ]:
a = torch.tensor([[1,2],[3,4]])
a

In [ ]:
b = a.transpose(0,1)
b

In [ ]:
a = torch.tensor([[[1,2],[3,4]],
                  [[5,6],[7,8]],
                  [[9,10],[11,12]]
                 ])
b = a.transpose(0,2)

In [ ]:
b

In [ ]:
print(a.stride())
print(b.stride())

In [ ]:
a = torch.tensor([[3,1,2],[4,1,7]])
b = a.transpose(0,1)
print(a[0,0])
b[0,0] = -1
print(a[0,0])

In [ ]:
a = torch.tensor([1,2],device = 'cuda')

In [ ]:
a = torch.tensor([[[1,2,3]]])
a.size()

In [ ]:
b = a.squeeze(dim=0)
b.size()

In [ ]:
c = a.squeeze()
c.size()

In [ ]:
d = c.unsqueeze(dim=1)
d.size()

In [ ]:
x = torch.randn(2, 3)
x1 = torch.cat((x,x),dim = 0)
x2 = torch.cat((x,x),dim = 1)

In [ ]:
x

In [ ]:
x1

In [ ]:
x2

In [ ]:
x = torch.randn(1, 3)
y = torch.randn(1, 3)
z = torch.where(x>y,x,y)

In [ ]:
print('x',x)
print('y',y)
print('z',z)

In [ ]:
#Broadcasting
x = torch.tensor([1,2,3])
y = torch.tensor([[-1],[0],[1]])
z = torch.ones((2,3,3),dtype = torch.int64)

print('x:',x.size())
print('y:',y.size())
print('z:',z.size())

u = x * y
v = x * z
w = y * z
print('u:',u.size())
print('v:',v.size())
print('w:',w.size())

In [ ]:
print('x:',x)
print('y:',y)
print('z:',z)

In [ ]:
print('u:',u)
print('v:',v)
print('w:',w)

In [ ]:
from PIL import Image

In [ ]:
img = np.asarray(Image.open('balloons.jpg'))

In [ ]:
import matplotlib.pyplot as plt

plt.imshow(img)
plt.show()

In [ ]:
img_tensor = torch.tensor(img).to(dtype = torch.float32)
print(img_tensor.size())

In [ ]:
weights = torch.tensor([0.2126,0.7152,0.0722])
weights.size()

In [ ]:
gray = torch.sum(weights * img_tensor,dim = 2)
gray.size()

In [ ]:
plt.imshow(gray,cmap = 'gray')
plt.show()

In [ ]:
img_tensor1 = img_tensor.permute([2,0,1])
img_tensor1.size()

In [ ]:
img_r,img_g,img_b = img_tensor1[0],img_tensor1[1],img_tensor1[2]

In [ ]:
fig, (ax1, ax2, ax3) = plt.subplots(1,3)
ax1.imshow(img_r.numpy(),cmap='gray'),ax1.axis('off')
ax2.imshow(img_g.numpy(),cmap='gray'),ax2.axis('off')
ax3.imshow(img_b.numpy(),cmap='gray'),ax3.axis('off')
plt.show()

In [ ]:
img_files = ['balloons.jpg','happydog.jfif','sunflower.jpg','Woolsthorpe-Manor.jpg']

img_batch = torch.zeros(len(img_files),3,480,640,dtype = torch.uint8)
print(img_batch.size())
for i,f in enumerate(img_files):
    img = np.array(Image.open(f).resize((640,480)))
    img_tensor = torch.from_numpy(img)
    img_tensor = img_tensor.permute(2,0,1)
    img_batch[i] = img_tensor
    

In [ ]:
#对图像进行标准化
img_batch = img_batch.float() / 255.0
mean = torch.tensor([0.485, 0.456, 0.406])
std = torch.tensor([0.229, 0.224, 0.225])

print('batch:',img_batch.size())
print('mean:',mean.size())
print('std:',std.size())

In [ ]:
mean_unsqueezed = mean.unsqueeze(dim = 1).unsqueeze(dim=1)
std_unsqueezed = std.unsqueeze(dim = 1).unsqueeze(dim = 1)
print(mean_unsqueezed.size())

In [ ]:
img_batch_normalized = (img_batch - mean_unsqueezed) / std_unsqueezed

## AutoGrad

In [ ]:
x = torch.tensor([1.0])
w = torch.tensor([1.0],requires_grad = True)
y = w*x

In [ ]:
print(w)

In [ ]:
print(y)

In [ ]:
loss = (y - 2)**2
print(loss)

In [ ]:
loss.backward(retain_graph=True)

In [ ]:
w.grad

In [ ]:
with torch.no_grad():
    w -= 0.1*w.grad

In [ ]:
print(w)

In [ ]:
print(loss)

In [ ]:
x = torch.tensor([1.0])
w = torch.tensor([1.0],requires_grad = True)
y = w*x

for epoch in range(3):
    print('epoch:%d'%(epoch))
    if w.grad is not None:
        w.grad.zero_()
    loss = (y - 2)**2
    print(w.grad)
    loss.backward(retain_graph=True)
    print(w.grad)


In [ ]:
#稍微复杂一点的计算图
x1 = torch.tensor([0.0],requires_grad = True)
x2 = torch.tensor([1.0],requires_grad = True)
x3 = torch.tensor([1.0],requires_grad = True)

y1 = x1 + x2
print('y1:',y1)

y2 = x2*x3
print('y2:',y2)

y3 = torch.tensor([1.0],requires_grad = True)

z = y1*y3 + y2
print('z:',z)

In [ ]:
z.grad_fn

一元线性回归:$y=w\times x+b$，假设真实的模型为$f(x) = 2\times x+1$。

In [ ]:
#生成训练数据
x = torch.rand(10)*10 - 5 #[-5,5]上的均匀分布随机数
y = 2*x + 1 + torch.randn(10) #受随机噪声污染的y

plt.plot(x.numpy(),y.numpy(),'*')
plt.plot(x.numpy(),2*x.numpy()+1,'r-')
plt.show()

In [ ]:
#定义回归模型
def linearReg(x,w,b):
    y = w * x + b
    return y

In [ ]:
#定义损失函数
def lossFn(y,y_hat):
    squared_errors = (y - y_hat)**2
    loss = squared_errors.mean()
    return loss

In [ ]:
#定义训练函数
def trainModel(x,y,w,b,epochs,lr = 0.1):   
    for epoch in range(1, epochs + 1):
        if w.grad is not None:
            w.grad.zero_()
        if b.grad is not None:
            b.grad.zero_()
            
        y_pred = linearReg(x,w,b)
        
        loss = lossFn(y_pred,y)
        
        loss.backward()
        
        with torch.no_grad():
            w -= lr * w.grad
            b -= lr * b.grad
        
        print('Epoch = %d, Loss = %f, w = %f,b = %f'%(
            epoch,loss.detach().numpy(),w.detach().numpy(),b.detach().numpy()))
    return w,b

In [ ]:
#训练模型
#初始化参数w,b
w = torch.tensor([0.0],requires_grad = True)
b = torch.tensor([0.0],requires_grad = True)
w,b = trainModel(x,y,w,b,epochs = 10, lr = 0.01)
w.requires_grad_ = False
b.requires_grad_ = False

In [ ]:
y_pred = linearReg(x,w,b)
plt.plot(x.numpy(),y.numpy(),'*')
plt.plot(x.numpy(),2*x.numpy()+1,'r-')
plt.plot(x.numpy(),y_pred.detach().numpy(),'ko')
plt.show()

In [ ]:
#稍微复杂一点的计算图:单隐层神经网络

x = torch.tensor([0.0,1.0])
w1 = torch.tensor([[0.1,0.1],[0.1,-0.1]],requires_grad = True)
b1 = torch.tensor([0.0],requires_grad = True)

z = torch.matmul(w1,x)+b1
w2 = torch.tensor([-0.3,0.2])
b2 = torch.tensor([0.0])

y = torch.matmul(w2,z)+b2

loss = (y - 1)**2

In [ ]:
loss

In [ ]:
loss.backward()

In [ ]:
print(w2.grad)

In [ ]:
print(w1.grad)

In [ ]:
torch.autograd.grad(loss,w1)

In [ ]:
x = torch.tensor([0.0,1.0])
w1 = torch.tensor([[0.1,0.1],[0.1,-0.1]],requires_grad = True)
b1 = torch.tensor([0.0],requires_grad = True)

z = torch.matmul(w1,x)+b1
w2 = torch.tensor([-0.3,0.2])
b2 = torch.tensor([0.0])

y = torch.matmul(w2,z)+b2

loss = (y - 1)**2

In [ ]:
loss.backward(retain_graph = True)

In [ ]:
print(w1.grad)

In [ ]:
torch.autograd.grad(loss,w1)

In [ ]:
#使用torch.optim训练一元线性回归
#定义训练函数
import torch.optim as optim

def trainModel(x,y,w,b,epochs,lr = 0.1):
    optimizer = optim.SGD([w,b],lr = lr)
    
    for epoch in range(1, epochs + 1):
#         if w.grad is not None:
#             w.grad.zero_()
#         if b.grad is not None:
#             b.grad.zero_()

        optimizer.zero_grad()
    
        y_pred = linearReg(x,w,b)
        
        loss = lossFn(y_pred,y)
        
        loss.backward()
        
#         with torch.no_grad():
#             w -= lr * w.grad
#             b -= lr * b.grad
        optimizer.step()
        
        print('Epoch = %d, Loss = %f, w = %f,b = %f'%(
            epoch,loss.detach().numpy(),w.detach().numpy(),b.detach().numpy()))
    return w,b

In [ ]:
#生成训练数据
x = torch.rand(10)*10 - 5 #[-5,5]上的均匀分布随机数
y = 2*x + 1 + torch.randn(10) #受随机噪声污染的y

plt.plot(x.numpy(),y.numpy(),'*')
plt.plot(x.numpy(),2*x.numpy()+1,'r-')
plt.show()

In [ ]:
w = torch.tensor([0.0],requires_grad = True)
b = torch.tensor([0.0],requires_grad = True)
w,b = trainModel(x,y,w,b,epochs = 10, lr = 0.01)
y_pred = linearReg(x,w,b)
plt.plot(x.numpy(),y.numpy(),'*')
plt.plot(x.numpy(),2*x.numpy()+1,'r-')
plt.plot(x.numpy(),y_pred.detach().numpy(),'ko')
plt.show()

## Torch.nn

In [ ]:
import torch.nn as nn    

In [ ]:
linReg = nn.Linear(1,1)

In [ ]:
#生成训练数据
x = torch.rand(10)*10 - 5 #[-5,5]上的均匀分布随机数
y = 2*x + 1 + torch.randn(10) #受随机噪声污染的y

plt.plot(x.numpy(),y.numpy(),'*')
plt.plot(x.numpy(),2*x.numpy()+1,'r-')
plt.show()

In [ ]:
print(x.shape)

In [ ]:
y_pred = linReg(x.view(10,1))
plt.plot(x.numpy(),y.numpy(),'*')
plt.plot(x.numpy(),2*x.numpy()+1,'r-')
plt.plot(x.numpy(),y_pred.detach().numpy(),'ko')
plt.show()

In [ ]:
#训练线性回归
linReg = nn.Linear(1,1)

loss_fn = nn.MSELoss(reduction='mean')

linReg.train()

optimizer = optim.SGD(params = linReg.parameters(),lr = 0.1,momentum = 0.9)

for epoch in range(10):

    optimizer.zero_grad()
    
    y_pred = linReg(x.view(10,1))  

    loss = loss_fn(y_pred, y)

    loss.backward()

    optimizer.step()

    print("epoch:", epoch, "loss",loss.data.item())

for param in linReg.parameters():
    print(param)

### Logistic Regression

In [ ]:
import csv
def readData(csvfile):
    with open(csvfile) as f:
        reader = csv.reader(f, delimiter=',')
        fields = next(reader)
        x = []
        y = []
        for row in reader:
            if '' in row:
                continue
                
            f = [float(v) for v in row[0:-1]]
            x.append(f)
            y.append(float(row[-1]))
        
        return np.array(x),np.array(y)

In [ ]:
x_train,y_train = readData('circle-train.csv')

print(x_train[0,:])
print(y_train.shape)

plt.figure()
plt.axis('equal')
plt.plot(x_train[y_train==0,0],x_train[y_train==0,1],'r*')
plt.plot(x_train[y_train==1,0],x_train[y_train==1,1],'ko')
plt.show()

In [ ]:
x = torch.tensor(x_train,dtype = torch.float32)
y = torch.tensor(y_train[:,np.newaxis],dtype = torch.float)

logReg = nn.Linear(2,1)
loss_fn = nn.BCEWithLogitsLoss()

logReg.train()

optimizer = optim.SGD(params = logReg.parameters(),lr = 0.1,momentum = 0.9)

for epoch in range(10):

    optimizer.zero_grad()
    
    y_pred = logReg(x) 

    loss = loss_fn(y_pred, y)

    loss.backward()

    optimizer.step()

    print("epoch:", epoch, "loss",loss.data.item())

for param in logReg.parameters():
    print(param)

### MNIST

In [ ]:
from torchvision import datasets,transforms

data_path = '../data/'
mnist_train = datasets.MNIST(data_path,download=True,train = True,transform = transforms.ToTensor())
mnist_test =  datasets.MNIST(data_path,download=True,train = False,transform = transforms.ToTensor())

In [ ]:
len(mnist_test)

In [ ]:
img,label = mnist_train[0]

In [ ]:
img.shape

In [ ]:
label.data

In [ ]:
img = img.view(-1)
img.shape

In [ ]:
img.max()

In [ ]:
train_loader = torch.utils.data.DataLoader(mnist_train, batch_size = 32, shuffle = True)

In [ ]:
#MLP
mnist_mlp = nn.Sequential(nn.Linear(784,64),
                         nn.Sigmoid(),
                         nn.Linear(64,10),
                         nn.Softmax(dim = 1))

optimizer = optim.SGD(mnist_mlp.parameters(), lr = 0.01)

loss_fn = nn.CrossEntropyLoss()

epochs = 10
mnist_mlp.train()
for epoch in range(epochs):
    for imgs, labels in train_loader:
        batch_size = imgs.shape[0]
        prob = mnist_mlp(imgs.view(batch_size,-1))
        loss = loss_fn(prob,labels)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        
    print('Epoch:%d, Loss:%f'%(epoch,loss.detach().numpy()))

In [ ]:
#测试模型
test_loader = torch.utils.data.DataLoader(mnist_test, batch_size = 100, shuffle = False)
mnist_mlp.eval()
correct = 0
total = 0
with torch.no_grad():
    for imgs,labels in test_loader:
        batch_size = imgs.shape[0]
        prob = mnist_mlp(imgs.view(batch_size,-1))
        _,predicted = torch.max(prob.data,1)
        total += batch_size
        correct += (predicted == labels).sum().item()
        
acc = correct / total

print('acc:',acc)